config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#stories'
  get 'story', to: 'home#story'
end

app/models/application_record.rb
# frozen_string_literal: true

# Abstract class for ActiveRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Handle routing request for Home
class HomeController < ApplicationController
  def stories
    @news = StoriesParsing.new
    @news.parse
  end

  def story
    @story = StoryParsing.new(params[:url], params[:image])
    @story.parse
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Shared helper methods for all views
module ApplicationHelper
end

app/views/home/stories.html.haml
- @news.stories.each do |story|
  .row
    .col-sm-3
      - if story[:image].present?
        = image_tag(story[:image], class: 'img-thumbnail')
      - else
        = image_tag('hackernews.png', class: 'img-thumbnail')
    .col-sm-9
      .row
        %div
          = link_to story[:title], story_path(url: story[:url], image: story[:image]), target: :_blank
      .row
        %div
          = "#{story[:excerpt].split.first(25).join(' ')}..."
  %hr

app/views/home/story.html.haml
- if @story.error
  .row
    %div{class: 'article-error'}
      Something is wrong with the original article. Please try again later.
- else
  - if @story.image.present?
    .row
      = image_tag(@story.image, class: 'img-fluid')
    %hr
  .row
    = sanitize(@story.content)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HackerNews
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.container
    = yield